luxonis/XLink

- CMakeLists.txt
- shared/src/XLinkData.c
- shared/src/XLinkDispatcherImpl.c
- tests/CMakeLists.txt
- tests/multiple_open_stream.cpp
Backwards compatible for for desynchronization of opening streams from both device and host side.
Closes #6
- Added a test for future reference.
- The fix itself is in `shared/src/XLinkDispatcherImpl.c`
> Stream desynchronization fix

- src/pc/PlatformData.c
- src/pc/PlatformDeviceControl.c
Addresses open issue regarding building on macOS and a missing `MSG_NOSIGNAL` flag.
Close: #16
> Crossplatform way of disabling SIGPIPE signal

- include/XLink/XLink.h
- src/shared/XLinkDevice.c
Adds a timeout version of remote reset, to add in cases where read/writes gets blocked indefinitely (when device doesn't indicate connection failure properly - TCP case specific)
> Remote reset timeout function

- include/XLink/XLinkErrorUtils.h
- include/XLink/XLinkPlatformErrorUtils.h
- src/pc/PlatformDeviceControl.c
XLink is calling exit() in some situations which force terminates the main app. Naturally, a library should not do this -- it should instead return error values or throw. As this is C code, it should return error values.
Related issue luxonis/depthai-core#257
1. I do not have a test harness to test the change in `PlatformDeviceControl.c`. It is dependent on `USE_USB_VSC` not defined....yet the cmake for the project seems to always define it in CMakefiles.txt line 56. So perhaps this is a non-issue.
2. Also in `PlatformDeviceControl.c` line 538 is likely errant code. Memset is using the character `0` aka value 48 and not the value zero. As I look at the struct...this doesn't look correct. It is not an exit() issue so I haven't included a code change...but...suspicious. Compare to line 650.
> replace exit() calls -- they force terminate the main app in trivial situations

- src/pc/PlatformData.c
- src/pc/PlatformDeviceControl.c
Because of a missing `signal.h` include, `SIGPIPE` wasn't defined, which ignored setting the `MSG_NOSIGNAL` on writes.
Removed actual `SIGPIPE` check and left only `MSG_NOSIGNAL` and `SO_NOSIGPIPE` which are defined in `sys/socket.h`
Checked against macOS and Linux
> Fixed regression ignoring SIGPIPE signal

- include/XLink/XLinkPrivateFields.h
- src/shared/XLinkDevice.c
- src/shared/XLinkPrivateFields.c
Scenario this attempts to resolve is the following:
Two threads try to connect to separate devices at the same time. In XLinkConnect:
- T1, calls `getNextAvailableLink` and retrieves a pointer to a xLinkDesc_t entry (eg first entry). Entry isn't yet marked as used and is returned as is.
- T2, calls `getNextAvailableLink` and retrieves same pointer (eg first entry), because T1 didn't yet assign a valid ID to the link (happens later in `XLinkConnect`)
After this both threads modify the same entry.
This PR combines retrieving the next available link with assigning a valid ID to it. If it later shows that link isn't needed, it can be "freed" by setting it an invalid ID again and destroying the previously created semaphore.
> XLinkConnect thread safety

- include/XLink/XLink.h
- include/XLink/XLinkMacros.h
- include/XLink/XLinkPrivateDefines.h
- src/shared/XLinkData.c
- src/shared/XLinkDispatcher.c
- src/shared/XLinkDispatcherImpl.c
- src/shared/XLinkPrivateFields.c
- src/shared/XLinkStream.c
This is the xlink portion of work to fix https://github.com/luxonis/depthai-core/issues/257
I request review of this PR for approach, style, and validity. 🔍👍
* enables move semantic for ownership of packet data/memory using C.
* adds public xlink APIs for move, move w/ timeout, and deallocating
* ready to be used by my pending PR to depthai-core to use these move semantics
I have added comments/notes highlighting bugs with `BUGBUG` and suggested future work `TODO`.
I fully intend to forcepush an update as we discuss and resolve concerns.
My first approach was to create a new `xLinkEventType_t::XLINK_READ_MOVE_REQ`. This required far too much change/coordination for handshakes, coordination of local/remote fill levels, etc. I discarded this work. 😝
My second approach (this PR) is to use …
> add move semantics for XLink packets

- include/XLink/XLink.h
- src/shared/XLinkData.c
Fixes XLinkReadMove functionality for multiple devices.
TLDR, "public functions" like XLinkReleaseData, require the "full" streamId, which consists of 8 MSB bits designated to linkId and 24 LSB bits which are designed to the actual streamId. 
XLinkReadMove had an issue where it called XLinkReleaseData with streamId which had its linkId "extracted" (set to zero). This caused the event to go to another link (eg first link, with ID 0) instead of the correct link.
Most changes are only to prevent similar issues in the future, by renaming the actual streamId to streamIdOnly.
> XlinkReadMove fix

- include/XLink/XLinkMacros.h
Fix `warning: multiple unsequenced modifications to...` circular buffer macros.
I could not repro this warning on Win vs2019, U20.04, U21.10, clang, gcc, debug ,release, static, or dynamic builds.
Reading the C-spec, I could imagine how a compile might be unclear on the sequence. So I've updated the first macro with hope @szabi-luxonis will no longer have the warning when they compile it on their test harness.
Continues to compile clean and run well on my test machines and all test+examples pass.
As discussed with @szabi-luxonis  https://github.com/luxonis/XLink/pull/29/files/5d2d5023aff5caed817a47fae36e761347af8018#r789119871
> fix warning: multiple unsequenced modifications in circ buf macros

- CMakeLists.txt
- src/pc/PlatformData.c
- src/pc/protocols/usb_host.cpp
PlatformData.c:
Cast size to size_t in chunk size initialization to avoid sign compare error in
comparison.
CMakeLists.txt:
Support specifying XLINK_LIBUSB_LOCAL D flag (results in no hunter dependencies
being needed for building).
> Move libusb include above XLink platform includes

- src/pc/PlatformDeviceControl.c
Unrelated, also replaced non thread-safe `strtok` usage.
> Set `TCP_NODELAY` to potentially reduce latency

- CMakeLists.txt
- cmake/XLink.cmake
- include/XLink/XLinkPlatform.h
- src/pc/PlatformDeviceControl.c
- src/pc/Win/src/win_usb_host.cpp
- src/pc/protocols/usb_host.cpp
- src/pc/protocols/usb_host.h
- src/shared/XLinkDevice.c
NOT READY FOR MERGE
This PR controls the location in which Windows searches+loads the libusb DLL.
The libusb DLL should be in the same folder as the binary code that is/contains XLink. The primary config of depthai-core is to have a static XLink that is linked into depthai-core. Therefore...
1. If you have shared lib (aka DLL) of depthai-core, then libusb DLL should be in the same folder as depthai-core.dll
2. If you have static lib depthai-core, then your main app "contains" depthai-core. Then, libusb DLL should be in the same folder as your main app.
3. If you customed and compiled your own depthai-core so that XLink is a separate shared lib (aka DLL), then libusb DLL should be in the same folder as XLink.dll. This is probably a rare scenario.
* uses Windows delay-load …
> add control of libusb DLL on Windows

- CMakeLists.txt
Fixes issue mentioned here: https://github.com/luxonis/depthai-core/issues/505
I tested this with https://github.com/ibaiGorordo/depthai-android-jni-example replacing the libdepthai-core.so and depthai+xlink includes with what I built locally using this fix with depthai-core v2.16.0 and it seemed to work fine
> Add Android logging dependencies

- src/pc/PlatformDeviceSearch.c
fix luxonis/XLink#54 by correcting misuse of `memset()`
> fix wrong use of memset()

- src/pc/PlatformDeviceSearch.c
fix luxonis/XLink#56 buy removing the duplicate decrement of `sizeFoundDevices`
I also caution that `src\pc\PlatformDeviceSearch.c` lines 89 and 120 are missing a dangerous scenario. If `numFoundDevices > sizeFoundDevices` that means that memory was overwritten/corrupted. That scenario must never occur. This PR does not address that danger.
> remove dup decrement for TCPIP device searches

- src/pc/protocols/usb_host.cpp
complete refactor of `getWinUsbMxId()` to fix luxonis/XLink#57
Ready for review. Some things to keep in mind
* I've temporarily increased the log level to MVLOG_FATAL in this function for debug+test. I will decrease it before ready for merge.
* Movidius MyriadX usb devices often change their usb path when they load their bootloader/firmware
* Since USB is dynamic, it is technically possible for a device to change its path at any time
* I learned that USB host controllers each have exactly one root usb hub. It is a 1:1 relationship. I use that to find usb root hubs faster using a GUID specific to host controllers.
* libusb creates its usb path "x.x.x.x" during `libusb_get_device_list()` using a single snapshot of the entire PCI+USB tree using the same `SetupDiGetClassDevsA()` Win32 api. …
> refactor getWinUsbMxId() to fix luxonis/XLink#57

- src/shared/XLinkDevice.c
- src/shared/XLinkDispatcher.c
Fix `getNextAvailableLinkUniqueId` to always increment the next returned id. In certain cases it returned the previous link id, and even if the connection got closed (mainly by device after FW boot), there might have been queued transfers (like the blocking readback after bootMemory in DepthAI) interfering with the newly open connection on the same id.
@diablodale's comment in https://github.com/luxonis/XLink/commit/5d2d5023aff5caed817a47fae36e761347af8018 also relevant:
> TODO investigate race condition that is (probably) later caught                              
due to changing the global `xLinkDesc_t availableXLinks[MAX_LINKS]`                          
without any thread protection. The dispatcher thread can be calling this function            
while an app thread calls …
> Multi-threading fix, link IDs were reused in certain cases

- README.md
It took me a while to understand where XLink does come from. The good news is that in a sense this repo is not a fork anymore, as there is no other public XLink repo that I could found.
> Update README.md with reference to XLink origin

- CMakeLists.txt
- include/XLink/XLinkLog.h
The variable `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` used to support `BUILD_SHARED_LIBS` works fine for all symbols, except static/global variable (see https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html and https://www.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/).
For this reason, the global symbols need to be explicitly exported via `__declspec(dllexport)` and `__declspec(dllimport)`, that are added via a `XLinkExport.h` header generated by the `generate_export_header` CMake function. 
Without this fix, linking an executable against the `XLink` shared library on Windows fails with error:
~~~
FAILED: examples/boot_firmware.exe
C:\Windows\system32\cmd.exe /C "cd . && D:\miniforge3\envs\idjlluxonisenv\Library\bin\cmake.exe -E …
> Enable support for BUILD_SHARED_LIBS on Windows

- examples/CMakeLists.txt
- examples/xlink_client_local.cpp
- examples/xlink_server_local.cpp
- src/pc/PlatformData.c
- src/pc/protocols/local_memshd.cpp
- src/pc/protocols/tcpip_memshd.cpp
- src/shared/XLinkData.c
- src/shared/XLinkDispatcher.c
- src/shared/XLinkDispatcherImpl.c
Fixed the handling of file streaming when not using a compatible protocol with SHDMEM.
> Fixed shdmem bugs and handled fd streaming

- .github/workflows/.dev.workflow.yml
- CMakeLists.txt
- src/pc/protocols/usb_host.cpp
Adds Clang support
Fixes issues:
https://github.com/luxonis/XLink/issues/80
https://github.com/luxonis/depthai-core/issues/1044
> Clang Support

- .gitignore
- src/pc/protocols/tcpip_host.cpp
- src/pc/protocols/tcpip_host.h
Add extended discovery to mainline XLink, to allow detection discovery of RVC3/4 devices on mainline DepthAI.
> Add extended device discovery

- src/pc/protocols/pcie_host.c
XLink/src/pc/protocols/pcie_host.c:469:55: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 59 [-Wformat-truncation=]
469 |             snprintf(found_device, name_length, "/dev/%s", entry->d_name);
> pcie: Fix sprintf with XLINK_MAX_NAME_SIZE
